# Generated by Django 5.1.15 on 2026-09-03 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(help_text='Target region or valley (e.g. Hunza, Skardu, Fairy Meadows).', max_length=150)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft (Pending Traveler Approval)'), ('approved', 'Approved by Traveler'), ('inquiry_sent', 'Inquiry Sent to Operator')], default='draft', help_text='Human-in-the-Loop state: must be explicitly approved by the traveler before finalization.', max_length=30)),
                ('is_approved_by_user', models.BooleanField(default=False, help_text='Explicit approval flag set only upon direct visitor confirmation.')),
                ('approval_timestamp', models.DateTimeField(blank=True, help_text='Exact timestamp when the traveler confirmed this itinerary.', null=True)),
                ('itinerary_data', models.JSONField(default=dict, help_text='Structured day-by-day plan, inclusions, exclusions, and trek grading.')),
                ('source_verified_at', models.DateTimeField(blank=True, help_text='Data freshness timestamp recording when live data was scraped from itp.7scribes.com.', null=True)),
                ('estimated_price_pkr', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated or quoted price in PKR.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, help_text='The chat session where this itinerary was synthesized.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='chat.chatsession')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this saved itinerary. Null for guest session itineraries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Itinerary',
                'verbose_name_plural': 'Saved Itineraries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
