# Generated by Django 5.1.15 on 2026-09-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditinerary',
            name='confidence_label',
            field=models.CharField(default='from our official listing', help_text="Confidence label: 'from our official listing' or 'researched just now, unverified, please confirm with our team'.", max_length=150),
        ),
        migrations.AddField(
            model_name='saveditinerary',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Live URL from where this itinerary was verified.', max_length=500),
        ),
    ]
