# Generated by Django 5.1.15 on 2026-09-03 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Trip Plan', max_length=255)),
                ('is_guest', models.BooleanField(default=False, help_text='True if this session was initiated by an unauthenticated guest visitor.')),
                ('guest_token', models.CharField(blank=True, db_index=True, default='', help_text='Ephemeral client-side token scoped to the browser session for guest access verification.', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores session preferences such as destination region, duration, budget, fitness level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for guest sessions; linked for registered users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='Structured tool calls initiated by the model.')),
                ('tool_results', models.JSONField(blank=True, default=list, help_text='Structured tool outputs returned from MCP servers.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Timestamp of live scrape, grounding citations, confidence metrics.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
