# Generated by Django 5.1.15 on 2026-09-09 06:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text="Associated chat session ID (or 'default').", max_length=255)),
                ('skill', models.CharField(db_index=True, help_text='Skill that triggered this call (e.g. itinerary_lookup, region_coverage_check, web_search_fallback, itinerary_drafting, content_cleaning).', max_length=100)),
                ('tool_name', models.CharField(db_index=True, help_text='Name of the tool or execution step.', max_length=100)),
                ('status', models.CharField(db_index=True, default='success', help_text="Outcome status: 'success' or 'failed'.", max_length=20)),
                ('llm_provider', models.CharField(blank=True, default='', help_text="LLM provider and model handling this step (e.g. 'ollama:llama3.2:3b', 'groq:openai/gpt-oss-120b', or empty).", max_length=100)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Arguments or input payload for this tool call.')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Summary or structured result returned by the tool.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Captured error or exception message if the tool failed.')),
                ('duration_ms', models.FloatField(blank=True, help_text='Execution duration in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the tool call was executed.')),
            ],
            options={
                'verbose_name': 'Tool Call Log',
                'verbose_name_plural': 'Tool Call Logs',
                'ordering': ['created_at'],
            },
        ),
    ]
